name: Build LOVE Game

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read
  issues: read

env:
  # Product Information
  PRODUCT_NAME: "LOVE2D Starter Kit"
  # Build Configuration
  OUTPUT_FOLDER: "./build"
  PRODUCT_FILE: "love-2d-starter-kit"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
            
      - name: Create output directory
        run: mkdir -p build
        
      - name: Build LOVE package
        run: |
          # Make the build script executable and run it
          chmod +x ./utils/build-love.sh
          ./utils/build-love.sh
            
      - name: Upload .love artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PRODUCT_FILE }}.love
          path: ${{ env.OUTPUT_FOLDER }}/${{ env.PRODUCT_FILE }}.love
              
      - name: Create tools directory
        run: mkdir -p ./tools

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick
        
      - name: Build HTML package
        run: |
          curl -fsSL --retry 5 --retry-delay 15 --connect-timeout 30 --max-time 300 https://github.com/2dengine/love.js/archive/refs/heads/main.zip -o ./tools/love.js.zip || exit 1
          unzip -q ./tools/love.js.zip -d ./tools/
          sed -i "s/<title>löve.js<\/title>/<title>${{ env.PRODUCT_NAME }}<\/title>/" ./tools/love.js-main/index.html
          sed -i '/<base href="\/play\/">$/d' ./tools/love.js-main/index.html
          sed -i "s/player.min.js/player.min.js?g=game.love/" ./tools/love.js-main/index.html
          convert ./assets/icon.png -define icon:auto-resize="256,128,96,64,48,32,24,16" ./tools/love.js-main/favicon.ico
          mkdir -p "${{ env.OUTPUT_FOLDER }}/${PRODUCT_FILE}-html"
          rsync -a --exclude='.htaccess' --exclude='*.git*' --exclude='*.md' --exclude='*.txt' \
            ./tools/love.js-main/ \
            ${{ env.OUTPUT_FOLDER }}/${PRODUCT_FILE}-html/
          cp -v ${{ env.OUTPUT_FOLDER }}/${PRODUCT_FILE}.love ${{ env.OUTPUT_FOLDER }}/${PRODUCT_FILE}-html/game.love
          7z a -tzip \
            "${{ env.OUTPUT_FOLDER }}/${PRODUCT_FILE}-html.zip" \
            "${{ env.OUTPUT_FOLDER }}/${PRODUCT_FILE}-html"/*
            
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PRODUCT_FILE }}-html
          path: ${{ env.OUTPUT_FOLDER }}/${{ env.PRODUCT_FILE }}-html